---
options:
  global: ""  # used once at the end of the command
  local:      # used for every workflow
    - "-b"
    - "--configuration json://$JSON"
    - "--aod-memory-rate-limit 2000000000"
    - "--shm-segment-size 16000000000"
    - "--resources-monitoring 2"
    - "--min-failure-level error"

workflows:
  # dummy workflow with the full list of options
  o2-analysis-workflow:
    executable: o2-analysis-workflow  # workflow command, if different from the dictionary node name above
    dependencies: []  # dictionary nodes that this workflow needs as direct dependencies (format: str, list)
    requires_mc: no  # yes/no whether the workflow can only run on MC or not
    options: "--option"  # command line options (format: str, list), see more detailed format below
    # options:
    #   default: ""
    #   real: ""
    #   mc: "--doMC"
    tables: []  # descriptions of output tables to be saved as trees (format: str, list), see more detailed format below
    # tables:
    #   default: []
    #   real: []
    #   mc: []

  # Helper tasks

  o2-analysis-track-to-collision-associator:
    tables: HFTRACKASSOC

  o2-analysis-timestamp: {}

  o2-analysis-trackselection_run2:
    executable: o2-analysis-trackselection
    dependencies: o2-analysis-track-dca_run2

  o2-analysis-trackselection_run3:
    executable: o2-analysis-trackselection
    dependencies: o2-analysis-track-dca_run3

  o2-analysis-trackselection_run5:
    executable: o2-analysis-alice3-trackselection

  o2-analysis-track-dca_run2:
    executable: o2-analysis-trackextension
    dependencies: o2-analysis-timestamp

  o2-analysis-track-dca_run3:
    executable: o2-analysis-track-propagation
    dependencies: o2-analysis-timestamp

  o2-analysis-track-dca_run5:
    executable: o2-analysis-alice3-trackextension

  o2-analysis-centrality_run2:
    executable: o2-analysis-centrality-table

  o2-analysis-centrality_run3:
    executable: o2-analysis-centrality-table

  o2-analysis-centrality_run5:
    executable: o2-analysis-alice3-centrality
    dependencies: o2-analysis-track-dca_run5

  o2-analysis-event-selection:
    dependencies: o2-analysis-timestamp

  o2-analysis-multiplicity-table_run2:
    executable: o2-analysis-multiplicity-table

  o2-analysis-multiplicity-table_run3:
    executable: o2-analysis-multiplicity-table
    dependencies: o2-analysis-event-selection

  o2-analysis-ft0-corrected-table: {}

  # PID

  o2-analysis-pid-tpc-base: {}

  o2-analysis-pid-tpc:
    dependencies: [o2-analysis-pid-tpc-base, o2-analysis-timestamp]

  o2-analysis-pid-tof-base_run2:
    executable: o2-analysis-pid-tof-base
    dependencies: o2-analysis-event-selection

  o2-analysis-pid-tof-base_run3:
    executable: o2-analysis-pid-tof-base
    dependencies: [o2-analysis-event-selection, o2-analysis-ft0-corrected-table]

  o2-analysis-pid-tof-full_run2:
    executable: o2-analysis-pid-tof-full
    dependencies: [o2-analysis-pid-tof-base_run2, o2-analysis-timestamp]

  o2-analysis-pid-tof-full_run3:
    executable: o2-analysis-pid-tof-full
    dependencies: [o2-analysis-pid-tof-base_run3, o2-analysis-timestamp]

  o2-analysis-pid-tof-full_run5:
    executable: o2-analysis-alice3-pid-tof

  o2-analysis-pid-bayes:
    dependencies: [o2-analysis-pid-tof-full_runX, o2-analysis-pid-tpc, o2-analysis-multiplicity-table_runX]

  o2-analysis-pid-tof-beta: {}

  # Converters

  o2-analysis-mc-converter: {}

  o2-analysis-fdd-converter: {}

  o2-analysis-collision-converter: {}

  o2-analysis-zdc-converter: {}

  o2-analysis-bc-converter: {}

  o2-analysis-tracks-extra-converter: {}

  o2-analysis-v0converter: {}

  # LF

  o2-analysis-lf-lambdakzerobuilder:
    dependencies: [o2-analysis-timestamp, o2-analysis-track-dca_runX, o2-analysis-pid-tpc]
